### ISSUE TITLE
Cannot scrap mech parts

### ISSUE THREAD

**Issue by victorlapin** [mad2342/EvenTheOdds#1]
Hello, Mad! I really like your mods and I'm using a ton of them. However, I've encountered a little issue with this one. I cannot sell salvaged parts of the P Mechs. Clicking "Sell" from the mech bay does nothing. Also, P mech parts do not stack with vanilla parts of the same chassis.

All I have in EvenTheOdds.log:

[EvenTheOdds @ 08.10.2020 18:26:04] CLEANED UP
----------------------------------------------------------------------------------------------------
[EvenTheOdds @ 08.10.2020 18:26:04] EXCEPTION:
Message: Sequence contains no elements<br/>
StackTrace:   at System.Linq.Enumerable.First[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00010] in <1b13ba6391c74847bbc3eddc86df7eee>:0 
  at Logger.OverrideDebugLevel (System.String modName) [0x0003b] in <96ef3e8eb4dc49ba839c8667b2feb847>:0 
----------------------------------------------------------------------------------------------------

Maybe there is a known conflicting mods list that I could check up with? I'm using 1.8.1-002R version.

**Comment by mad2342** [comment]
Hi victorlapin,

Thx for the report!
The error message is not complete, but probably only relating to you not havin my logging setup, so no problem with actual game logic there.
In vanilla you cannot sell MechParts on their own, so most likely you're using some mod which enables that and probably conflicts. I don't have that issue and i'm still playing from time to time with this mod enabled all the time.
The patch for replacing the "P-MechDef" with the vanilla MechDef during Salvage-Generation is actually very simple so i really think there's a conflict with some other mod patching the same method.
Could you try and play a mission with only EvenTheOdds enabled and see if the problem persists?
Probably a look at the game's "output_log.txt" could help too..
Best regards, Mad

**Comment by victorlapin** [comment]
In vanilla I sure can scrap mech parts for c-bills =) maybe some bad wording from my end, sorry for that. I use Loot Magnet and Custom Salvage, though, so there's still a possibility for conflict.

**Comment by victorlapin** [comment]
Okay, I have some errors tagged with CustomComponents. Will investigate.

**Comment by victorlapin** [comment]
So I've found a bunch of lines in output_log.txt:

Data.DataManager.ContainedLoadRequest [ERROR] ManifestEntry is null for [Weapon_Laser_MediumLaser_3-Ceres_Arms] [WeaponDef] - resourceIds are case sensitive, so be sure to check that too

is it related to your latest commit in this repo?

**Comment by mad2342** [comment]
Hi victorlapin,
I see, you meant **scrap**, ok. I looked at the related methods in game source and these will potentially break if the custom MechDefs won't get "normalized" to the stock ones at Salvage-Gen. Should never happen though (or at least throw an exception).
BTW, how do you actually know that you're trying to scrap a "P-MechPart"? Are there some indications in the UI?

**Comment by mad2342** [comment]
Hmm, didn't you mention output regarding missing WeaponDefs in another comment? Because i can't see that comment anymore...
There actually was a hidden dependency to another mod of mine in the MechDefs of ETO, they used custom weapons not known to Vanilla. It's probably not related but i fixed it in the current release nevertheless. -> 1.9.1-001R

**Comment by victorlapin** [comment]
I'll give it a try then. About that comment, yeah, I got confused by WeaponDefs and decided not to distract you any further

**Comment by victorlapin** [comment]
> BTW, how do you actually know that you're trying to scrap a "P-MechPart"? Are there some indications in the UI?

No visual difference in the game, I just tend to remember "P" Mechs encountered in a mission (tougher opponents, you know). So, for example, I've met an Enforcer-P, then got part of vanilla Enforcer. I still can use it to build the Enforcer if I have enough parts. The one and only problem is - they don't stack with pure vanilla parts and cannot be scrapped.

The issue is still there with 1.9.1-001R, though no more error messages about WeaponDefs. Can I provoke P-Mechs to spawn somehow? I'd start a new campaign with pure vanilla + modtek + even the odds, but it'll take some time to bump into them.

**Comment by mad2342** [comment]
You could arrive at a planet, take note of a mission, leave game, edit the contract.json and put the custom MechDefs in there (targetTeam.lanceOverrideList.unitSpawnPointOverrideList.unitDefId), return to game, play.

**Comment by victorlapin** [comment]
And even more to it, if I uninstall EvenTheOdds, ex-P-Mech parts disappear. So there's something that marks them as custom in some way.

**Comment by victorlapin** [comment]
This is what I get when loading a saved game and going to MechBay, without EvenTheOdds, but with CustomSalvage:

> CustomSalvage [ERROR] ERROR: mechdef_victor_VTR-9S_P not found
> CustomSalvage [ERROR] ERROR: mechdef_enforcer_ENF-4R_P not found
> CustomSalvage [ERROR] ERROR: mechdef_locust_LCT-1S_P not found
> CustomSalvage [ERROR] ERROR: mechdef_wolverine_WVR-6R_P not found

Before you ask, without CustomSalvage those mech parts aren't scrappable as well. But it's clear to me that when you pick up salvaged ex-P-mech part, its mechdef is still P one, and not vanilla.

What else can I do to help you debug this thing?

**Comment by mad2342** [comment]
See this: [https://github.com/BattletechModders/CustomSalvage/blob/master/source/Patches/Contract_GenerateSalvage.cs](https://github.com/BattletechModders/CustomSalvage/blob/master/source/Patches/Contract_GenerateSalvage.cs)
Author of Custom Salvage *replaces* the whole method "Contract.GenerateSalvage", thus my patched version of "Contract.CreateAndAddMechPart" (which is called in the original) never gets to replace the "wrong" MechDefs with the normalized ones. Without analyzing it further (and with all due respect) i suspect suboptimal code there.
No way to fix it without the author fixing *his* code.

But this explains it, the parts actually *are* P-Parts and thus the game gets confused when trying to scrap sth. that isn't known (most likely it tries to fetch a corresponding Chassis which doesn't exist in MDDB, like "chassisdef_wolverine_WVR-6R_P" and fails).

**Comment by victorlapin** [comment]
Ah, I see, so as long as the salvage is generated with CustomSalvage in place, it will be borked. Sorry for disturbance, then.
